name: Build and deploy Node.js app to Azure Web App - soucustomer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd /home/runner/work/aoai-realtime-audio-sdk/aoai-realtime-audio-sdk/javascript/samples/web  # サブディレクトリに移動
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip /home/runner/work/aoai-realtime-audio-sdk/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          cd /home/runner/work/aoai-realtime-audio-sdk/aoai-realtime-audio-sdk/  # サブディレクトリに移動

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_303BE5B1E9E2424490974AB5CC757EC4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6454D8ECE497483791CC70D7F28EE9E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0FD006F6C42546F1804BA4B67BE862D6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'soucustomer'
          slot-name: 'Production'
          package: /home/site/wwwroot/aoai-realtime-audio-sdk # サブディレクトリを指定
